# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171130_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
