# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171130_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='next_question_id',
            new_name='next_question',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
    ]
