# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171130_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=900),
        ),
    ]
