# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20171222_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=900),
        ),
    ]
